# https://taskfile.dev

version: '3'

vars:
  GREETING: Hello, World!

tasks:
  build:
    interactive: true
    cmds:
      - npx quartz build --serve

  sync:
    interactive: true
    cmd: npx quartz sync
